-- Metadata-only company catalog. Sources are fetched only after at least one
-- user follows them. Every board below was verified against its public ATS API
-- on 2026-08-18.
INSERT INTO job_sources (provider, external_key, company_name, career_url, config, enabled, featured)
VALUES
  ('amazon', 'amazon-jobs', 'Amazon', 'https://www.amazon.jobs/en/search', '{"searchQueries":["intern","co-op","student"]}', true, false),
  ('greenhouse', 'anthropic', 'Anthropic', 'https://job-boards.greenhouse.io/anthropic', '{"boardToken":"anthropic"}', true, false),
  ('greenhouse', 'figma', 'Figma', 'https://job-boards.greenhouse.io/figma', '{"boardToken":"figma"}', true, false),
  ('greenhouse', 'reddit', 'Reddit', 'https://job-boards.greenhouse.io/reddit', '{"boardToken":"reddit"}', true, false),
  ('greenhouse', 'discord', 'Discord', 'https://job-boards.greenhouse.io/discord', '{"boardToken":"discord"}', true, false),
  ('greenhouse', 'datadog', 'Datadog', 'https://job-boards.greenhouse.io/datadog', '{"boardToken":"datadog"}', true, false),
  ('greenhouse', 'cloudflare', 'Cloudflare', 'https://job-boards.greenhouse.io/cloudflare', '{"boardToken":"cloudflare"}', true, false),
  ('greenhouse', 'coinbase', 'Coinbase', 'https://job-boards.greenhouse.io/coinbase', '{"boardToken":"coinbase"}', true, false),
  ('greenhouse', 'brex', 'Brex', 'https://job-boards.greenhouse.io/brex', '{"boardToken":"brex"}', true, false),
  ('greenhouse', 'affirm', 'Affirm', 'https://job-boards.greenhouse.io/affirm', '{"boardToken":"affirm"}', true, false),
  ('greenhouse', 'asana', 'Asana', 'https://job-boards.greenhouse.io/asana', '{"boardToken":"asana"}', true, false),
  ('greenhouse', 'dropbox', 'Dropbox', 'https://job-boards.greenhouse.io/dropbox', '{"boardToken":"dropbox"}', true, false),
  ('greenhouse', 'mongodb', 'MongoDB', 'https://job-boards.greenhouse.io/mongodb', '{"boardToken":"mongodb"}', true, false),
  ('greenhouse', 'samsara', 'Samsara', 'https://job-boards.greenhouse.io/samsara', '{"boardToken":"samsara"}', true, false),
  ('greenhouse', 'scaleai', 'Scale AI', 'https://job-boards.greenhouse.io/scaleai', '{"boardToken":"scaleai"}', true, false),
  ('greenhouse', 'andurilindustries', 'Anduril', 'https://job-boards.greenhouse.io/andurilindustries', '{"boardToken":"andurilindustries"}', true, false),
  ('greenhouse', 'spacex', 'SpaceX', 'https://job-boards.greenhouse.io/spacex', '{"boardToken":"spacex"}', true, false),
  ('greenhouse', 'neuralink', 'Neuralink', 'https://job-boards.greenhouse.io/neuralink', '{"boardToken":"neuralink"}', true, false),
  ('greenhouse', 'roblox', 'Roblox', 'https://job-boards.greenhouse.io/roblox', '{"boardToken":"roblox"}', true, false),
  ('greenhouse', 'lyft', 'Lyft', 'https://job-boards.greenhouse.io/lyft', '{"boardToken":"lyft"}', true, false),
  ('greenhouse', 'doordashusa', 'DoorDash', 'https://job-boards.greenhouse.io/doordashusa', '{"boardToken":"doordashusa"}', true, false),
  ('greenhouse', 'instacart', 'Instacart', 'https://job-boards.greenhouse.io/instacart', '{"boardToken":"instacart"}', true, false),
  ('greenhouse', 'pinterest', 'Pinterest', 'https://job-boards.greenhouse.io/pinterest', '{"boardToken":"pinterest"}', true, false),
  ('greenhouse', 'twilio', 'Twilio', 'https://job-boards.greenhouse.io/twilio', '{"boardToken":"twilio"}', true, false),
  ('greenhouse', 'okta', 'Okta', 'https://job-boards.greenhouse.io/okta', '{"boardToken":"okta"}', true, false),
  ('greenhouse', 'hubspotjobs', 'HubSpot', 'https://job-boards.greenhouse.io/hubspotjobs', '{"boardToken":"hubspotjobs"}', true, false),
  ('greenhouse', 'gitlab', 'GitLab', 'https://job-boards.greenhouse.io/gitlab', '{"boardToken":"gitlab"}', true, false),
  ('greenhouse', 'elastic', 'Elastic', 'https://job-boards.greenhouse.io/elastic', '{"boardToken":"elastic"}', true, false),
  ('greenhouse', 'toast', 'Toast', 'https://job-boards.greenhouse.io/toast', '{"boardToken":"toast"}', true, false),
  ('greenhouse', 'duolingo', 'Duolingo', 'https://job-boards.greenhouse.io/duolingo', '{"boardToken":"duolingo"}', true, false),
  ('greenhouse', 'waymo', 'Waymo', 'https://job-boards.greenhouse.io/waymo', '{"boardToken":"waymo"}', true, false),
  ('greenhouse', 'lucidmotors', 'Lucid Motors', 'https://job-boards.greenhouse.io/lucidmotors', '{"boardToken":"lucidmotors"}', true, false),
  ('greenhouse', 'verkada', 'Verkada', 'https://job-boards.greenhouse.io/verkada', '{"boardToken":"verkada"}', true, false),
  ('greenhouse', 'gusto', 'Gusto', 'https://job-boards.greenhouse.io/gusto', '{"boardToken":"gusto"}', true, false),
  ('greenhouse', 'chime', 'Chime', 'https://job-boards.greenhouse.io/chime', '{"boardToken":"chime"}', true, false),
  ('greenhouse', 'carta', 'Carta', 'https://job-boards.greenhouse.io/carta', '{"boardToken":"carta"}', true, false),
  ('greenhouse', 'flexport', 'Flexport', 'https://job-boards.greenhouse.io/flexport', '{"boardToken":"flexport"}', true, false),
  ('greenhouse', 'airtable', 'Airtable', 'https://job-boards.greenhouse.io/airtable', '{"boardToken":"airtable"}', true, false),
  ('greenhouse', 'faire', 'Faire', 'https://job-boards.greenhouse.io/faire', '{"boardToken":"faire"}', true, false),
  ('greenhouse', 'nuro', 'Nuro', 'https://job-boards.greenhouse.io/nuro', '{"boardToken":"nuro"}', true, false),
  ('greenhouse', 'relativity', 'Relativity Space', 'https://job-boards.greenhouse.io/relativity', '{"boardToken":"relativity"}', true, false),
  ('greenhouse', 'robinhood', 'Robinhood', 'https://job-boards.greenhouse.io/robinhood', '{"boardToken":"robinhood"}', true, false),
  ('greenhouse', 'webflow', 'Webflow', 'https://job-boards.greenhouse.io/webflow', '{"boardToken":"webflow"}', true, false),
  ('greenhouse', 'cockroachlabs', 'Cockroach Labs', 'https://job-boards.greenhouse.io/cockroachlabs', '{"boardToken":"cockroachlabs"}', true, false),
  ('greenhouse', 'digitalocean98', 'DigitalOcean', 'https://job-boards.greenhouse.io/digitalocean98', '{"boardToken":"digitalocean98"}', true, false),
  ('greenhouse', 'canonical', 'Canonical', 'https://job-boards.greenhouse.io/canonical', '{"boardToken":"canonical"}', true, false),
  ('greenhouse', 'databricks', 'Databricks', 'https://job-boards.greenhouse.io/databricks', '{"boardToken":"databricks"}', true, false),
  ('lever', 'spotify', 'Spotify', 'https://jobs.lever.co/spotify', '{"site":"spotify"}', true, false),
  ('ashby', 'notion', 'Notion', 'https://jobs.ashbyhq.com/notion', '{"board":"notion"}', true, false),
  ('ashby', 'linear', 'Linear', 'https://jobs.ashbyhq.com/linear', '{"board":"linear"}', true, false),
  ('ashby', 'perplexity', 'Perplexity', 'https://jobs.ashbyhq.com/perplexity', '{"board":"perplexity"}', true, false),
  ('ashby', 'replit', 'Replit', 'https://jobs.ashbyhq.com/replit', '{"board":"replit"}', true, false),
  ('ashby', 'ashby', 'Ashby', 'https://jobs.ashbyhq.com/ashby', '{"board":"ashby"}', true, false)
ON CONFLICT (provider, external_key) DO UPDATE SET
  company_name = EXCLUDED.company_name,
  career_url = EXCLUDED.career_url,
  config = EXCLUDED.config,
  enabled = true;

NOTIFY pgrst, 'reload schema';
